export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID';
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
export const ORDER_COUNTRIES_BY_NAME = 'ORDER_COUNTRIES_BY_NAME';
export const ORDER_COUNTRIES_BY_POPULATION = 'ORDER_COUNTRIES_BY_POPULATION';
